FROM php:5.6-apache

RUN apt-get update -y && \
    apt-get install -y mlocate \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install -j$(nproc) gd && \
    docker-php-ext-install mysql mysqli && \
    cp /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/
