FROM hyperf/hyperf:7.3-alpine-cli

# Install composer deps
ADD . /hyperf-skeleton

# Install composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer self-update --clean-backups \
    && cd /hyperf-skeleton \
    && composer install \
    && composer clearcache
